### ISSUE TITLE
Feature request: auto-close files when using context managers

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/pyasdf#111] opened 2015-04-26 16:19 UTC
In the following example:

```python
import numpy as np
from pyasdf import AsdfFile

tree = {'test': np.array([1,2,3])}

f = AsdfFile(tree)
f.set_array_storage(tree['test'], 'inline')
f.write_to('data.asdf')

for i in range(1000):
    with AsdfFile.read('masked.asdf') as f2:
        np.sum(f2.tree['test'])
```

I am running into:

```
OSError: [Errno 24] Too many open files
```

It would be nice if ``read`` could work as a normal context manager and auto-close the file.

**Comment by mdboom** [comment] 2015-04-28 15:15
I think this is a side effect of often needing to keep the file open for either the `update` method or memmapping the arrays.  If we close the file in either of those cases, it will go "boom".  I suspect this is resolvable, but one does end up with behavior that's a little surprising, such as this not working:

```
with AsdfFile.read('masked.asdf') as f2:
    pass
x = f2.tree['test']
```

**Comment by mdboom** [comment] 2015-04-28 15:38
Actually, are you sure this isn't working?  I can't reproduce, and it should (and seemingly does) close the file after each with block is exited.

**Comment by astrofrog** [comment] 2015-04-28 21:53
With the exact script above, I get:

```
Traceback (most recent call last):
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/numpy/ma/core.py", line 2709, in __new__
    mask = np.array(mask, copy=copy, dtype=mdtype)
TypeError: __array__() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ttt.py", line 12, in <module>
    np.sum(f2.tree['test'])
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/numpy/core/fromnumeric.py", line 1716, in sum
    sum = a.sum
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/pyasdf-0.0.dev426-py3.4.egg/pyasdf/tags/core/ndarray.py", line 309, in __getattr__
    return getattr(self._make_array(), attr)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/pyasdf-0.0.dev426-py3.4.egg/pyasdf/tags/core/ndarray.py", line 223, in _make_array
    self._array = self._apply_mask(self._array, self._mask)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/pyasdf-0.0.dev426-py3.4.egg/pyasdf/tags/core/ndarray.py", line 228, in _apply_mask
    return ma.array(array, mask=mask)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/numpy/ma/core.py", line 5883, in array
    fill_value=fill_value, ndmin=ndmin, shrink=shrink)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/numpy/ma/core.py", line 2712, in __new__
    mask = np.array([tuple([m] * len(mdtype)) for m in mask],
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/numpy/ma/core.py", line 2712, in <listcomp>
    mask = np.array([tuple([m] * len(mdtype)) for m in mask],
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/pyasdf-0.0.dev426-py3.4.egg/pyasdf/tags/core/ndarray.py", line 312, in __getitem__
    return self._make_array()[item]
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/pyasdf-0.0.dev426-py3.4.egg/pyasdf/tags/core/ndarray.py", line 221, in _make_array
    shape, self._dtype, block.data,
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/pyasdf-0.0.dev426-py3.4.egg/pyasdf/block.py", line 776, in data
    self.data_offset, self._size)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/pyasdf-0.0.dev426-py3.4.egg/pyasdf/generic_io.py", line 605, in memmap_array
    self._fd, mode=mode, offset=offset, shape=size)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/site-packages/numpy/core/memmap.py", line 270, in __new__
    self.filename = os.path.abspath(filename.name)
  File "/Users/tom/miniconda3/envs/production/lib/python3.4/posixpath.py", line 361, in abspath
    cwd = os.getcwd()
OSError: [Errno 24] Too many open files
```

This is on MacOS X with Python 3, in case this matters?

**Comment by mdboom** [comment] 2015-04-29 00:17
Ok -- I see it now.  The file must contain a masked array in order to reproduce.  (This was hidden a bit because the example writes to a file called 'test.asdf', but reads a file called 'masked.asdf').  With that, I can reproduce it just about anywhere.  I fear this may be a reference bug in `np.ma`, but I'm not done investigating yet.

**Comment by mdboom** [comment] 2015-04-29 01:02
See #117.  The issue is not that the context manager is not closing the file -- passing a memmapped array as a mask to a numpy MaskedArray causes the memmap reference to never be freed, thus keeping the file open.  Making a view of the mask array seems to resolve this (not quite sure why though).

**Comment by astrofrog** [comment] 2015-04-29 10:45
@mdboom - that was a pretty subtle issue - good catch! :)

**Closed** 2015-04-29 16:58 UTC
